[package]
name = "e4-2_02_mutable_references"
version = "0.1.0"
authors = ["Dominic Torruellas <dom@domtorr.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
